version: "3.8"
services: 
    db:
        image: mariadb
        volumes: 
            - type: volume
              source: mariadb_sf
              target: /var/lib/mysql
        ports: 
            - 3306:3306
        env_file: 
            - ./app/.env.local
    php:
        build: 
            context: ./php
            dockerfile: Dockerfile
        volumes:
            - type: bind
              source: ./app
              target: /app
        ports: 
            - 8000:8000
        env_file: 
            - ./php/.env
        depends_on: 
            - db
volumes: 
    mariadb_sf:
        external: true