version: "3.8"
services: 
    db:
        image: mariadb
        volumes: 
            - type: volume
              source: mariadb_sf
              target: /var/lib/mysql
        ports: 
            - 3306:3306
        environment: 
            - MARIADB_ROOT_PASSWORD
    php:
        build: .
        volumes:
            - type: bind
              source: ./
              target: /app
        ports: 
            - 8000:8000
        env_file: 
            - .env
volumes: 
    mariadb_sf:
        external: true